sudo: required

language: r 

r:
  - release

env: SCIDB_VER=16.9

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    --publish 8083:8083
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done

install:
  - git clone https://github.com/ksens/scidbr.git
  - R CMD build scidbr 

script:
  - SCIDB_TEST_HOST=127.0.0.1 R CMD check scidb_2.0.0.tar.gz

after_failure:
  - docker logs scidb
