# blocklist
branches:
  except:
  - discontinued_master

sudo: required

language: r
cache: packages

addons:
  apt:
    packages:
      - pandoc
      - libxml2-dev

r:
  - release

#r_packages:
#  - knitr

env: SCIDB_VER=16.9

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    --publish 8083:8083
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done

# install:
#   - R --slave -e "install.packages(c('knitr', 'bit64', 'curl', 'data.table', 'openssl'))"
#   - cd ..
#   - R CMD build SciDBR

# script:
#   - SCIDB_TEST_HOST=127.0.0.1 R CMD check scidb_*.tar.gz

install:
  - R -e "install.packages(c('knitr', 'bit64', 'curl', 'data.table', 'openssl', 'devtools'))"
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - SCIDB_TEST_HOST=127.0.0.1 R CMD check *tar.gz

after_failure:
  - docker logs scidb
